[package]
name = "code_editor"
version = "0.2.0"
edition = "2021"

[dependencies]
eframe = "0.22"
egui = "0.22"
tokio = { version = "1.0", features = ["full"] }
rfd = "0.10"
syntect = "5.0"
walkdir = "2"

[dependencies.winapi]
version = "0.3"
features = ["winuser", "windef"]
